### PR TITLE
Added .gitignore & a very nice class

### PR DESCRIPTION
**Pull request by redraskal**
This is a very premium pull request that creates the best .gitignore on the planet & it even contains a very random class that I just created! Since you had the Spigot repo in the pom.xml, I made a very premium class that can change the max player count on a Spigot server while its online.

The UselessButUsefulFeature class is even documented!

### CODE REVIEW

**Comment by AndrewAubury** [comment]
Hmm this seems like it could be Five stars but. can it spawn a chicken ;)

**Comment by wherkamp** [comment]
Update the mc version. and I will accept it.

**Comment by redraskal** [comment]
> Hmm this seems like it could be Five stars but. can it spawn a chicken ;)

no sorry this class isn't good enough for that

**Comment by redraskal** [comment]
It works on 1.13.1 now 😃

**Comment by wherkamp** [comment]
I was talking about the raven. :)

**Comment by redraskal** [comment]
oh xd well now you get both

**Pull request merged**
